name: Update README on Commit or Merge

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README
        uses: shravan20/aquila@dff91aeed7b8ba90938d44085b136d8e75c61aa4
        with:
          content: 'This is custom content added on every commit or merge.'
