name: Update README on Commit or Merge

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README
        uses: /Users/shravan/personal/aquila
        with:
          content: 'This is custom content added on every commit or merge.'
